/**
 * Generated by /model-creator for the "what-are-the-needs-of-the-user" n8n automation.
 * Could not get a structured answer from the response-shape check (error); assuming the standard shape.
 * @module @deepseek-ai/dsh-what-are-the-needs-of-the-user
 */

import { randomUUID } from 'node:crypto'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { Context, Service } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-host-webserver'
// Pulls in this module's `declare module '@deepseek-ai/cordis'` augmentation
// too, which is what makes `ctx.get('credentials')` below typecheck.
import { credentialRef, isCredentialRefName } from '@deepseek-ai/dsh-credentials'

declare module '@deepseek-ai/cordis' {
  interface Context {
    whatAreTheNeedsOfTheUserBridge: BridgeController
  }
}

export interface BridgeConfig {
  webhookUrl: string
  apiKey: string
  modelId: string
  path?: string
  /**
   * Character budget for the session title this route derives for its own
   * detected title-generation requests (see `SESSION_TITLE_REQUEST_PREFIX`
   * below) instead of spending an n8n call on them.
   * @default 60
   */
  sessionTitleMaxChars?: number
  /**
   * How this route answers its own detected session-title requests: `'llm'`
   * (the default) asks a real model to summarize the request into a short
   * title, falling back to local truncation on any failure -- bad or
   * missing key, network error, timeout, or a malformed response -- so a
   * title is always produced. `'local'` always truncates instead, with no
   * network call. (Same mechanism already applied by hand in
   * permaculture-model-bridge; ported here so every /model-creator-generated
   * bridge gets it too.)
   * @default 'llm'
   */
  titleMode?: 'local' | 'llm'
  /**
   * Name of the credential reference (or env var) holding the API key sent
   * to `titleLlmBaseUrl`. Resolved through `ctx.credentials` first -- same
   * as a built-in provider's `apiKeyEnv`, so a key already entered for, say,
   * the `openrouter` provider is found here too -- then through a literal
   * `process.env` lookup. Only used when `titleMode` is `'llm'`.
   * @default 'OPENROUTER_API_KEY'
   */
  titleLlmApiKeyEnv?: string
  /** Model id sent to `titleLlmBaseUrl` for title generation. @default 'anthropic/claude-sonnet-5' */
  titleLlmModel?: string
  /** OpenAI Chat Completions-compatible endpoint called for title generation. @default 'https://openrouter.ai/api/v1/chat/completions' */
  titleLlmBaseUrl?: string
  /** Deadline for the title-generation request, in milliseconds, before falling back to local truncation. @default 15000 */
  titleLlmTimeoutMs?: number
}

interface ResolvedConfig {
  webhookUrl: string
  apiKey: string
  modelId: string
  path: string
  sessionTitleMaxChars: number
  titleMode: 'local' | 'llm'
  titleLlmApiKeyEnv: string
  titleLlmModel: string
  titleLlmBaseUrl: string
  titleLlmTimeoutMs: number
}

const DEFAULT_PATH = '/what-are-the-needs-of-the-user/v1/chat/completions'
const DEFAULT_SESSION_TITLE_MAX_CHARS = 60
const DEFAULT_TITLE_MODE: 'local' | 'llm' = 'llm'
const DEFAULT_TITLE_LLM_API_KEY_ENV = 'OPENROUTER_API_KEY'
const DEFAULT_TITLE_LLM_MODEL = 'anthropic/claude-sonnet-5'
const DEFAULT_TITLE_LLM_BASE_URL = 'https://openrouter.ai/api/v1/chat/completions'
const DEFAULT_TITLE_LLM_TIMEOUT_MS = 15000

function resolveConfig(config: unknown): ResolvedConfig {
  if (typeof config !== 'object' || config === null) {
    throw new Error('BridgeConfig must be an object')
  }
  const record = config as Record<string, unknown>
  const webhookUrl = record.webhookUrl
  if (typeof webhookUrl !== 'string' || webhookUrl.trim() === '') {
    throw new Error('BridgeConfig needs a non-empty string `webhookUrl`')
  }
  const apiKey = record.apiKey
  if (typeof apiKey !== 'string' || apiKey.trim() === '') {
    throw new Error('BridgeConfig needs a non-empty string `apiKey`')
  }
  const modelId = record.modelId
  if (typeof modelId !== 'string' || modelId.trim() === '') {
    throw new Error('BridgeConfig needs a non-empty string `modelId`')
  }
  const path = record.path
  const titleMode = record.titleMode === 'local' || record.titleMode === 'llm' ? record.titleMode : DEFAULT_TITLE_MODE
  return {
    webhookUrl,
    apiKey,
    modelId,
    path: (path as string | undefined) ?? DEFAULT_PATH,
    sessionTitleMaxChars: (record.sessionTitleMaxChars as number | undefined) ?? DEFAULT_SESSION_TITLE_MAX_CHARS,
    titleMode,
    titleLlmApiKeyEnv: (record.titleLlmApiKeyEnv as string | undefined) ?? DEFAULT_TITLE_LLM_API_KEY_ENV,
    titleLlmModel: (record.titleLlmModel as string | undefined) ?? DEFAULT_TITLE_LLM_MODEL,
    titleLlmBaseUrl: (record.titleLlmBaseUrl as string | undefined) ?? DEFAULT_TITLE_LLM_BASE_URL,
    titleLlmTimeoutMs: (record.titleLlmTimeoutMs as number | undefined) ?? DEFAULT_TITLE_LLM_TIMEOUT_MS,
  }
}

/** Extracts the answer text from the webhook's raw response body. */
function parseAnswer(raw: string): string {

  let answer = raw
  try {
    const data: unknown = JSON.parse(raw)
    if (typeof data === 'string') {
      answer = data
    } else if (data !== null && typeof data === 'object' && typeof (data as Record<string, unknown>).output === 'string') {
      answer = (data as Record<string, unknown>).output as string
    }
  } catch {
    // Not JSON — fall back to the raw response body as-is.
  }
  return answer.trim()
}

async function fetchGroundedAnswer(
  config: ResolvedConfig,
  question: string,
  sessionId: string | undefined,
): Promise<string> {
  const response = await fetch(config.webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chatInput: question,
      ...sessionId === undefined ? {} : { sessionId },
    }),
  })
  if (!response.ok) throw new Error(`n8n webhook returned HTTP ${response.status}`)
  const raw = await response.text()
  const answer = parseAnswer(raw)
  if (answer === '') throw new Error('n8n webhook returned an empty response')
  return answer
}

function readRequestBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    req.on('data', (chunk: Buffer) => chunks.push(chunk))
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')))
    req.on('error', reject)
  })
}

/**
 * Parse an OpenAI-style message 'content' field (plain string or
 * content-part array) into its text. Only text parts are used -- this
 * bridge sends only plain text to n8n.
 */
function extractTextContent(content: unknown): string | undefined {
  if (typeof content === 'string') return content
  if (!Array.isArray(content)) return undefined

  const textParts: string[] = []
  for (const part of content) {
    if (part === null || typeof part !== 'object') continue
    const record = part as Record<string, unknown>
    if (record.type === 'text' && typeof record.text === 'string') textParts.push(record.text)
  }

  return textParts.length === 0 ? undefined : textParts.join('\n')
}

/**
 * Prefixes DSH's own agent loop appends, as additional trailing `role:
 * "user"` messages, after the person's real turn -- a "workspace instructions"
 * reminder and a "current runtime context" snapshot. A naive "just take the
 * last user message" extraction picks up one of these instead of what the
 * person actually typed. DSH may add more such synthetic messages over
 * time; widen this list rather than assume the last `user` message is
 * always the real one. (Same fix already applied by hand in
 * permaculture-model-bridge; ported here so every /model-creator-generated
 * bridge gets it too.)
 */
const SYNTHETIC_CONTEXT_PREFIXES = ['<system-reminder>', 'Current runtime context.']

/** Whether an extracted user-turn text is one of DSH's own injected context messages rather than something the person typed. */
function isSyntheticContext(text: string): boolean {
  return SYNTHETIC_CONTEXT_PREFIXES.some(prefix => text.startsWith(prefix))
}

/**
 * Find the person's actual last message text, skipping synthetic context
 * messages.
 */
function extractLastUserText(messages: unknown): string | undefined {
  if (!Array.isArray(messages)) return undefined
  for (let i = messages.length - 1; i >= 0; i -= 1) {
    const m = messages[i] as Record<string, unknown>
    if (m?.role !== 'user') continue
    const text = extractTextContent(m.content)
    if (text === undefined || isSyntheticContext(text)) continue
    return text
  }
  return undefined
}

/**
 * The exact, stable prefix `@deepseek-ai/dsh-session-title-llm` frames its
 * one auxiliary request with. Recognizing this lets this route answer
 * session-title requests locally (or via a real model, per `titleMode`)
 * instead of forwarding them to n8n -- otherwise a live n8n run gets spent
 * summarizing nothing, and the answer comes back in the automation's own
 * voice instead of a short title. (Same fix already applied by hand in
 * permaculture-model-bridge; ported here so every /model-creator-generated
 * bridge gets it too.)
 */
const SESSION_TITLE_REQUEST_PREFIX = 'Generate the session title from this JSON array of human messages:\n'

interface SessionTitleSourceMessage {
  readonly text?: unknown
}

/** Parse a detected session-title request and return its first selected message's text, whitespace-collapsed and trimmed. */
function extractSessionTitleSourceText(requestText: string): string | undefined {
  const json = requestText.slice(SESSION_TITLE_REQUEST_PREFIX.length)
  let parsed: unknown
  try {
    parsed = JSON.parse(json)
  } catch {
    return undefined
  }
  if (!Array.isArray(parsed) || parsed.length === 0) return undefined
  const first = parsed[0] as SessionTitleSourceMessage
  if (typeof first.text !== 'string') return undefined
  const collapsed = first.text.replace(/\s+/g, ' ').trim()
  return collapsed === '' ? undefined : collapsed
}

/** Truncate `text` to `maxChars` on a word boundary, appending an ellipsis when cut. */
function truncateTitle(text: string, maxChars: number): string {
  if (text.length <= maxChars) return text
  const truncated = text.slice(0, maxChars)
  const lastSpace = truncated.lastIndexOf(' ')
  return `${lastSpace > 0 ? truncated.slice(0, lastSpace) : truncated}…`
}

/**
 * Derive a short title locally by truncating a detected session-title
 * request's first message. Also the fallback `titleMode: 'llm'` uses on
 * any failure.
 */
function deriveSessionTitle(requestText: string, maxChars: number): string | undefined {
  const collapsed = extractSessionTitleSourceText(requestText)
  return collapsed === undefined ? undefined : truncateTitle(collapsed, maxChars)
}

const TITLE_LLM_SYSTEM_PROMPT = 'Write a short session title (a few words, plain text, no quotes, no trailing punctuation) that summarizes the user message that follows. Reply with only the title -- no preamble, no explanation.'

/**
 * Resolve `name` to a secret value through `ctx.credentials` first,
 * falling back to a literal `process.env` lookup. Never throws -- a
 * resolution failure is just "not found" here.
 */
async function resolveTitleLlmApiKey(ctx: Context, name: string): Promise<string | undefined> {
  if (isCredentialRefName(name)) {
    const credentials = ctx.get('credentials')
    if (credentials !== undefined) {
      try {
        const resolved = await credentials.resolve(credentialRef(name))
        if (resolved !== undefined) return resolved.value
      } catch {
        // Fall through to the plain env-var check below.
      }
    }
  }
  return process.env[name]
}

/**
 * Ask a real model to summarize a detected session-title request into a
 * short title. Returns `undefined` on ANY failure, so the caller can fall
 * back to local truncation and still produce a title. Never throws.
 */
async function deriveSessionTitleViaLlm(ctx: Context, config: ResolvedConfig, requestText: string): Promise<string | undefined> {
  const apiKey = await resolveTitleLlmApiKey(ctx, config.titleLlmApiKeyEnv)
  if (!apiKey) return undefined

  const sourceText = extractSessionTitleSourceText(requestText)
  if (sourceText === undefined) return undefined

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), config.titleLlmTimeoutMs)
  try {
    const response = await fetch(config.titleLlmBaseUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: config.titleLlmModel,
        messages: [
          { role: 'system', content: TITLE_LLM_SYSTEM_PROMPT },
          { role: 'user', content: sourceText },
        ],
        max_tokens: 30,
        temperature: 0.3,
      }),
      signal: controller.signal,
    })
    if (!response.ok) return undefined

    const data: unknown = await response.json().catch(() => undefined)
    if (data === null || typeof data !== 'object') return undefined
    const choices = (data as Record<string, unknown>).choices
    if (!Array.isArray(choices) || choices.length === 0) return undefined
    const first = choices[0]
    if (first === null || typeof first !== 'object') return undefined
    const message = (first as Record<string, unknown>).message
    if (message === null || typeof message !== 'object') return undefined
    const content = (message as Record<string, unknown>).content
    if (typeof content !== 'string') return undefined

    const collapsed = content.replace(/\s+/g, ' ').trim().replace(/^["']|["']$/g, '')
    if (collapsed === '') return undefined
    return truncateTitle(collapsed, config.sessionTitleMaxChars)
  } catch {
    return undefined
  } finally {
    clearTimeout(timer)
  }
}

function writeSseAnswer(res: ServerResponse, modelId: string, answer: string): void {
  res.writeHead(200, { 'Content-Type': 'text/event-stream; charset=utf-8', 'Cache-Control': 'no-cache', Connection: 'keep-alive' })
  const id = `chatcmpl-${randomUUID()}`
  const created = Math.floor(Date.now() / 1000)
  res.write(`data: ${JSON.stringify({ id, object: 'chat.completion.chunk', created, model: modelId, choices: [{ index: 0, delta: { role: 'assistant', content: answer }, finish_reason: null }] })}\n\n`)
  res.write(`data: ${JSON.stringify({ id, object: 'chat.completion.chunk', created, model: modelId, choices: [{ index: 0, delta: {}, finish_reason: 'stop' }] })}\n\n`)
  res.write('data: [DONE]\n\n')
  res.end()
}

/**
 * DSH's own stable per-conversation identity, when the model config for this
 * bridge turns on long prompt-cache retention (`cacheRetention: 'long'` plus
 * `compat.supportsLongCacheRetention: true` on the model entry in
 * `settings.yaml`) -- pi-ai then puts `this.session.id` (clamped to 64
 * chars) on every request as `prompt_cache_key`, a field this bridge doesn't
 * otherwise use for caching but repurposes here as a stable session key, so
 * a stateful n8n workflow (Data Table session lookup, agent memory) can
 * actually continue a conversation turn to turn instead of restarting it on
 * every message. Absent (config not set, or an older DSH build) rather than
 * an error -- the bridge still answers, just without continuity, same as
 * before this existed.
 */
function extractSessionId(body: Record<string, unknown>): string | undefined {
  return typeof body.prompt_cache_key === 'string' && body.prompt_cache_key !== '' ? body.prompt_cache_key : undefined
}

async function handleChatCompletions(ctx: Context, config: ResolvedConfig, req: IncomingMessage, res: ServerResponse): Promise<void> {
  if (req.method !== 'POST') { res.writeHead(405).end(); return }
  if (req.headers.authorization !== `Bearer ${config.apiKey}`) { res.writeHead(401).end(); return }
  const raw = await readRequestBody(req)
  const body = JSON.parse(raw) as Record<string, unknown>
  if (body.model !== config.modelId) {
    res.writeHead(400, { 'Content-Type': 'application/json' }).end(JSON.stringify({ error: { message: 'unknown model', type: 'model_not_found' } }))
    return
  }
  const question = extractLastUserText(body.messages)
  if (!question) { res.writeHead(400).end(); return }
  const sessionId = extractSessionId(body)

  // Session-title requests aren't real questions for the automation --
  // answer them locally (or via a real model, per `titleMode`, falling back
  // to local on any failure); never spend an n8n call on one.
  if (question.startsWith(SESSION_TITLE_REQUEST_PREFIX)) {
    const title = config.titleMode === 'llm'
      ? (await deriveSessionTitleViaLlm(ctx, config, question)) ?? deriveSessionTitle(question, config.sessionTitleMaxChars)
      : deriveSessionTitle(question, config.sessionTitleMaxChars)
    if (title === undefined) { res.writeHead(502).end(); return }
    writeSseAnswer(res, config.modelId, title)
    return
  }

  try {
    const answer = await fetchGroundedAnswer(config, question, sessionId)
    writeSseAnswer(res, config.modelId, answer)
  } catch (error) {
    res.writeHead(502, { 'Content-Type': 'application/json' }).end(JSON.stringify({ error: { message: String(error), type: 'upstream_error' } }))
  }
}

export class BridgeController extends Service {
  static inject = ['webServer']

  constructor(ctx: Context, rawConfig: BridgeConfig) {
    super(ctx, 'whatAreTheNeedsOfTheUserBridge')
    const config = resolveConfig(rawConfig)
    ctx.webServer.register({ kind: 'prefix', path: config.path, handler: (req, res) => handleChatCompletions(ctx, config, req, res) })
  }
}

export default BridgeController
